version: '3'

services:

# 스파크
# 스파크 마스터
  spark-master:
    build:
      context: .
      dockerfile: ./spark/Dockerfile 
    image: sona-spark:0.1
    container_name: spark-master
    ports:
      - 8083:8083 # master webui
      - 7077:7077 # master port
    environment:
      - SPARK_MODE=master
      - SPARK_MASTER_HOST=spark-master
      - SPARK_MASTER_PORT=7077
      - SPARK_MASTER_WEBUI_PORT=8083
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    volumes: 
      - ./spark:/spark-work
    networks:
      - sona

# 스파크 워커2개
  spark-worker:
    build:
      context: .
      dockerfile: ./spark/Dockerfile 
    image: sona-spark:0.1

    environment:
      - SPARK_MODE=worker
      - SPARK_MASTER=spark://spark-master:7077
      - SPARK_WORKER_MEMORY=2G
      - SPARK_WORKER_CORES=2
      - NVIDIA_VISIBLE_DEVICE=0
    deploy:
      replicas: 1
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
        #     ports:
        #       - 18080-18089:8081
        #     volumes:
        #       - shared-workspace:/opt/workspace
    depends_on:
      - spark-master
    networks:
      - sona

networks:
  sona :
    driver: bridge
    external: true
    internal: true
